name: inkino
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  xml: ^2.6.0
  flutter_redux: ^0.3.5
  intl: ^0.15.2
  url_launcher: ^2.0.1
  path_provider: ^0.3.1
  connectivity: ^0.2.1
  shared_preferences: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^2.2.2

flutter:
  uses-material-design: true
  assets:
  - assets/preloaded_data/theaters.xml
  - assets/images/1x1_transparent.png
  - assets/images/powered_by_tmdb.png